### ISSUE TITLE
Work around Twitter API for Timeframe 

### ISSUE THREAD

**Issue by Muakasan** [PoliSee/PoliSee#3]
Figure out the way to collect twitter data over a large period of time ie 3 months:

- How expensive is the paid plan?

- How long can we scrape for based on the unpaid plan?

- Is it realistic to continuously scrape tweets and save them?

**Comment by tdbeirne** [comment]
Link to small, somewhat unorganized note sheet: https://docs.google.com/document/d/1rpik3M7h8q302AuXSCacPDWCyuHxHcl-yhPZBYgLtIE/edit?usp=sharing

^This has some of the pricing information, a description of our options for getting tweets, and links to Twitter's prices for the different API tiers.
