### ISSUE TITLE
Most Popular Governor candidates

### ISSUE THREAD

**Issue by Muakasan** [PoliSee/PoliSee#4]
Find a way to get the most popular governor candidates in the Democrat and Republican party

- Is there an API which gets us the party, or candidate data?

- If not, is there a good way to scrape this data? (Perhaps check polling websites)

**Comment by D3nGL1** [comment]
I found Google API (https://developers.google.com/civic-information/)but not sure it is recently updated. The time label on it is 2015.
So I found the other API(https://medium.com/ndp-annotations/civic-and-political-apis-data-sets-and-websites-136fa63a0af1)
If we just need the name of representatives we can use this file (https://docs.google.com/spreadsheets/d/1peOepPqFLcThlNGJpJeUC4BkztRDwyP179SU2wwD5-w/edit?usp=sharing)

**Comment by D3nGL1** [comment]
If the above doesn't work here are some other site or API I found:
https://www.fec.gov/data/candidates/president/?election_year=2020&cycle=2020&election_full=true
https://votesmart.org/share/api#.W66d92hKg72
https://www.govtrack.us/developers
https://ballotpedia.org/List_of_candidates_running_in_U.S._Congress_elections,_2018#Alabama
